ksya/ha-nefiteasy

- __init__.py
- const.py
- switch.py
I added switches that represent the home presence detection for each registered user-profile.
Also fixed a small bug in re-connecting.
> Home entrance/presence detection

- custom_components/nefiteasy/const.py
- custom_components/nefiteasy/switch.py
Adds a switch to enable or disable the weather dependent function of Nefit Easy
> Add switch to enable or disable weather dependent functionality

- custom_components/nefiteasy/__init__.py
- custom_components/nefiteasy/climate.py
- custom_components/nefiteasy/config_flow.py
- custom_components/nefiteasy/const.py
- custom_components/nefiteasy/manifest.json
- custom_components/nefiteasy/nefit_entity.py
- custom_components/nefiteasy/sensor.py
- custom_components/nefiteasy/strings.json
- custom_components/nefiteasy/switch.py
- custom_components/nefiteasy/translations/en.json
- Remove platform setup from domains
- Import yaml to ConfigEntry
- Implement loading/unloading of ConfigEntry
- Fix code quality issues
> Implement import to ConfigEntry

- custom_components/nefiteasy/__init__.py
- custom_components/nefiteasy/climate.py
- custom_components/nefiteasy/config_flow.py
- custom_components/nefiteasy/manifest.json
- custom_components/nefiteasy/nefit_entity.py
- custom_components/nefiteasy/strings.json
- custom_components/nefiteasy/translations/en.json
- Add config flow step user
- Add device info
> Add config flow step user and device info

- custom_components/nefiteasy/sensor.py
- custom_components/nefiteasy/switch.py
> Always setup all switches and sensors

- custom_components/nefiteasy/nefit_entity.py
> Fix get_endpoint in nefit entity

- custom_components/nefiteasy/__init__.py
- custom_components/nefiteasy/climate.py
- custom_components/nefiteasy/config_flow.py
- custom_components/nefiteasy/nefit_entity.py
- custom_components/nefiteasy/switch.py
> Fix wrong display state of switches after switching

- custom_components/nefiteasy/__init__.py
- custom_components/nefiteasy/nefit_entity.py
- custom_components/nefiteasy/switch.py
> Fix home entrance detection

- custom_components/nefiteasy/__init__.py
- custom_components/nefiteasy/climate.py
- custom_components/nefiteasy/manifest.json
- custom_components/nefiteasy/nefit_entity.py
- custom_components/nefiteasy/strings.json
- custom_components/nefiteasy/switch.py
- Update unique id and device info to new HA structure
- Format code with black / isort / ...
> Cleanups 1

- custom_components/nefiteasy/__init__.py
Support for yaml can be removed, was only used for import. New users should add it through config flow.
> Remove yaml support (import)

- custom_components/nefiteasy/__init__.py
- custom_components/nefiteasy/const.py
- custom_components/nefiteasy/models.py
- custom_components/nefiteasy/nefit_entity.py
- custom_components/nefiteasy/select.py
- custom_components/nefiteasy/sensor.py
- custom_components/nefiteasy/switch.py
Clean up the code a bit, implement new types for sensor and make sure correct state class and device class is set always.
Fixes #74
> Refactor code, add device class and state class

- custom_components/nefiteasy/__init__.py
- custom_components/nefiteasy/const.py
- custom_components/nefiteasy/models.py
- custom_components/nefiteasy/number.py
- custom_components/nefiteasy/sensor.py
Add two entities, a switch to activate shower timer and a number to set shower timer duration.
Fixes #58
> Add shower timer

- custom_components/nefiteasy/climate.py
- custom_components/nefiteasy/const.py
Change DEVICE_CLASS_XXX to SensorDeviceClass.XXX
Change device_state_attributes to extra_state_attributes
Fixes #92
> Fix deprecation issues with newest HA (2021.12)

- custom_components/nefiteasy/sensor.py
> Round temperature sensor entities to one decimal

- custom_components/nefiteasy/switch.py
> Fix precense detection

- .github/workflows/pull.yml
- .github/workflows/push.yml
Update from 3.8 to 3.9, as support for 3.8 is discontinued in HA.
> Update python version in test job

- custom_components/nefiteasy/const.py
- tests/fixtures/nefit_data.json
Tested to work with my Nefit Easy thermostat
> Add actualPower sensor

- custom_components/nefiteasy/__init__.py
> Add additional try except block around init

- README.md
- custom_components/nefiteasy/const.py
Following the protocol here https://github.com/marcelrv/nefit_easy_protocol/blob/master/hc1-temperatureAdjustment.md . This can be useful to calibrate the temperature measurement against another sensor with higher accuracy.
> Add entity for temperatureAdjustment endpoint

- custom_components/nefiteasy/const.py
> Change deprecated constant

- custom_components/nefiteasy/__init__.py
> Revert "Fix blocking call during init"
